@startuml ClassTasks
package "Core Models" {
    class Task {
        +String id
        +String sourceId
        +String connectionInstanceId
        +String dataSourceId
        +String title
        +String description
        +Status status
        +Priority priority
        +DateTime createdAt
        +DateTime updatedAt
        +String syncStatus
    }
    
    class TimeEntry {
        +String id
        +String remoteId
        +String connectionInstanceId
        +String dataSourceId
        +DateTime startDate
        +DateTime endDate
        +Number timeSpent
        +String syncStatus
        +String timeStatus
    }
    
    Task "1" *-- "0..*" TimeEntry : possui
}
@enduml
